name: Update Timeline

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  update_timeline:
    runs-on: ubuntu-latest

    steps:
  - name: Checkout repository
    uses: actions/checkout@v3
  
  - name: Configure Git
    run: |
      git config --global user.email "thehiddenwiki2024@proton.me"
      git config --global user.name "The-Hidden-Wiki-URLs"
  
  - name: Pull the latest changes from the remote repository
    run: git pull --rebase

  - name: Add changes
    run: git add timeline.txt
  
  - name: Commit changes
    run: git commit -m "Auto-update timeline.txt" || echo "No changes to commit"
  
  - name: Push changes
    run: git push
