name: Auto Update Timeline

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  update_timeline:
    runs-on: ubuntu-latest

   steps:
  - name: Checkout repository
    uses: actions/checkout@v3
    with:
      # Fetches all history for all tags and branches
      fetch-depth: 0
  
  - name: Configure Git
    run: |
      git config --global user.email "thehiddenwiki2024@proton.me"
      git config --global user.name "The-Hidden-Wiki-URLs"
  
  - name: Reset local repository to remote state
    run: |
      git fetch origin
      git reset --hard origin/main
  
  - name: Make changes
    run: |
      # Example command to update timeline.txt
      echo "Update - $(date -u)" >> timeline.txt
  
  - name: Commit and push changes
    run: |
      git add timeline.txt
      git commit -m "Auto-update timeline.txt" || echo "No changes to commit"
      # Force push in this scenario is safer since we just reset to match remote
      git push origin HEAD:main --force
