name: Delete File

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute

jobs:
  delete-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete file
      run: |
        rm Tor-Hidden-Services.txt
        git config --global user.email "thehiddenwiki2024@proton.me"
        git config --global user.name "The-Hidden-Wiki-URLs"
        git commit -am "Delete Tor-Hidden-Services.txt"
        git push
